import type { Meeting } from "@/types/meeting"
import type { User, Client } from "@/types/user"
import type { Notification } from "@/types/notification"

// Usuario de demo para portafolio
export const demoUser: User = {
  id: "demo-user-1",
  correo: "demo@portfolio.com",
  nombre: "Usuario Demo",
  tipo: "Administrador",
}

// Usuarios de ejemplo
export const sampleUsers: User[] = [
  {
    id: "1",
    correo: "ana.garcia@techcorp.com",
    nombre: "Ana Garcia",
    tipo: "Gerente",
  },
  {
    id: "2",
    correo: "carlos.lopez@innovasoft.com",
    nombre: "Carlos Lopez",
    tipo: "Desarrollador",
  },
  {
    id: "3",
    correo: "maria.rodriguez@devstudio.com",
    nombre: "Maria Rodriguez",
    tipo: "Disenadora",
  },
  {
    id: "4",
    correo: "luis.martin@salescorp.com",
    nombre: "Luis Martin",
    tipo: "Vendedor",
  },
  {
    id: "5",
    correo: "patricia.vega@design.com",
    nombre: "Patricia Vega",
    tipo: "Directora",
  },
  {
    id: "6",
    correo: "roberto.silva@training.com",
    nombre: "Roberto Silva",
    tipo: "Capacitador",
  },
  {
    id: "7",
    correo: "sofia.ruiz@salescorp.com",
    nombre: "Sofia Ruiz",
    tipo: "Coordinadora",
  },
  {
    id: "8",
    correo: "pedro.sanchez@devstudio.com",
    nombre: "Pedro Sanchez",
    tipo: "Desarrollador",
  },
]

// Clientes de ejemplo
export const sampleClients: Client[] = [
  { id: "1", nombre: "TechCorp", activo: true },
  { id: "2", nombre: "InnovaSoft", activo: true },
  { id: "3", nombre: "DevStudio", activo: true },
  { id: "4", nombre: "SalesCorp", activo: true },
  { id: "5", nombre: "Design Studio", activo: true },
  { id: "6", nombre: "Training Co", activo: true },
  { id: "7", nombre: "Marketing Plus", activo: true },
  { id: "8", nombre: "Consulting Group", activo: true },
]

// Generar fechas dinamicas basadas en la fecha actual
const getRelativeDate = (daysOffset: number, hours: number, minutes: number = 0): Date => {
  const date = new Date()
  date.setDate(date.getDate() + daysOffset)
  date.setHours(hours, minutes, 0, 0)
  return date
}

// Reuniones de ejemplo con fechas distribuidas en 3 semanas (semana anterior, actual y siguiente)
export const generateSampleMeetings = (): Meeting[] => [
  // === SEMANA ANTERIOR (-7 a -1 dias) ===
  {
    id: "1",
    title: "Kickoff Proyecto Alpha",
    organizer: "Ana Garcia",
    company: "TechCorp",
    startTime: getRelativeDate(-7, 9, 0),
    endTime: getRelativeDate(-7, 11, 0),
    description: "Reunion de inicio del proyecto Alpha con revision de alcance y cronograma.",
    attendees: ["ana.garcia@techcorp.com", "carlos.lopez@techcorp.com"],
    status: "Cerrada",
    files: [],
    comments: [
      {
        id: "1",
        author: "Carlos Lopez",
        content: "El proyecto fue aprobado exitosamente.",
        createdAt: new Date(Date.now() - 7 * 86400000),
      },
    ],
  },
  {
    id: "2",
    title: "Revision de Codigo Sprint 4",
    organizer: "Maria Rodriguez",
    company: "DevStudio",
    startTime: getRelativeDate(-6, 14, 0),
    endTime: getRelativeDate(-6, 16, 0),
    description: "Revision del codigo desarrollado durante el sprint 4",
    attendees: ["maria.rodriguez@devstudio.com", "pedro.sanchez@devstudio.com"],
    status: "Cerrada",
    files: [],
    comments: [],
  },
  {
    id: "3",
    title: "Capacitacion Docker y Kubernetes",
    organizer: "Roberto Silva",
    company: "Training Co",
    startTime: getRelativeDate(-5, 10, 0),
    endTime: getRelativeDate(-5, 13, 0),
    description: "Capacitacion intensiva sobre contenedores y orquestacion",
    attendees: ["roberto.silva@training.com", "pedro.sanchez@devstudio.com", "carlos.lopez@innovasoft.com"],
    status: "Cerrada",
    files: [],
    comments: [],
  },
  {
    id: "4",
    title: "Reunion de Ventas Semanal",
    organizer: "Luis Martin",
    company: "SalesCorp",
    startTime: getRelativeDate(-4, 9, 0),
    endTime: getRelativeDate(-4, 10, 30),
    description: "Revision semanal de pipeline y prospectos",
    attendees: ["luis.martin@salescorp.com", "sofia.ruiz@salescorp.com"],
    status: "Cerrada",
    files: [],
    comments: [],
  },
  {
    id: "5",
    title: "Workshop Figma Avanzado",
    organizer: "Patricia Vega",
    company: "Design Studio",
    startTime: getRelativeDate(-3, 15, 0),
    endTime: getRelativeDate(-3, 18, 0),
    description: "Workshop sobre funcionalidades avanzadas de Figma",
    attendees: ["patricia.vega@design.com", "maria.rodriguez@devstudio.com"],
    status: "Cerrada",
    files: [],
    comments: [],
  },
  {
    id: "6",
    title: "Retrospectiva Sprint 4",
    organizer: "Pedro Sanchez",
    company: "DevStudio",
    startTime: getRelativeDate(-2, 14, 0),
    endTime: getRelativeDate(-2, 15, 30),
    description: "Retrospectiva del equipo sobre el sprint anterior",
    attendees: ["pedro.sanchez@devstudio.com", "maria.rodriguez@devstudio.com", "carlos.lopez@innovasoft.com"],
    status: "Cerrada",
    files: [],
    comments: [
      {
        id: "1",
        author: "Maria Rodriguez",
        content: "Excelente trabajo del equipo este sprint!",
        createdAt: new Date(Date.now() - 2 * 86400000),
      },
    ],
  },
  // === SEMANA ACTUAL (0 a 6 dias) ===
  {
    id: "7",
    title: "Reunion de Planificacion Q2",
    organizer: "Ana Garcia",
    company: "TechCorp",
    startTime: getRelativeDate(0, 9, 0),
    endTime: getRelativeDate(0, 11, 30),
    description: "Planificacion estrategica para el segundo trimestre del anio. Revisaremos objetivos, KPIs y asignacion de recursos.",
    attendees: ["ana.garcia@techcorp.com", "carlos.lopez@techcorp.com", "maria.rodriguez@techcorp.com"],
    status: "Abierta",
    files: [
      {
        id: "1",
        name: "Presentacion Q2.pptx",
        size: "2.5 MB",
        uploadedBy: "Ana Garcia",
        uploadedAt: new Date(),
        type: "application/vnd.ms-powerpoint",
      },
    ],
    comments: [
      {
        id: "1",
        author: "Carlos Lopez",
        content: "Podemos revisar el presupuesto de marketing?",
        createdAt: new Date(),
      },
    ],
  },
  {
    id: "8",
    title: "Demo del Producto v2.0",
    organizer: "Carlos Lopez",
    company: "InnovaSoft",
    startTime: getRelativeDate(0, 14, 0),
    endTime: getRelativeDate(0, 15, 0),
    description: "Demostracion de las nuevas funcionalidades del producto version 2.0",
    attendees: ["carlos.lopez@innovasoft.com", "laura.martinez@innovasoft.com"],
    status: "Opcional",
    files: [],
    comments: [],
  },
  {
    id: "9",
    title: "Reunion de Ventas Mensual",
    organizer: "Luis Martin",
    company: "SalesCorp",
    startTime: getRelativeDate(1, 16, 0),
    endTime: getRelativeDate(1, 17, 30),
    description: "Revision de objetivos de ventas y pipeline de clientes",
    attendees: ["luis.martin@salescorp.com", "sofia.ruiz@salescorp.com"],
    status: "Abierta",
    files: [],
    comments: [],
  },
  {
    id: "10",
    title: "Revision de Codigo Sprint 5",
    organizer: "Maria Rodriguez",
    company: "DevStudio",
    startTime: getRelativeDate(2, 11, 0),
    endTime: getRelativeDate(2, 13, 0),
    description: "Revision semanal del codigo desarrollado durante el sprint",
    attendees: ["maria.rodriguez@devstudio.com", "pedro.sanchez@devstudio.com"],
    status: "Abierta",
    files: [],
    comments: [],
  },
  {
    id: "11",
    title: "Workshop de Diseno UX/UI",
    organizer: "Patricia Vega",
    company: "Design Studio",
    startTime: getRelativeDate(3, 15, 30),
    endTime: getRelativeDate(3, 18, 0),
    description: "Workshop intensivo de diseno UX/UI con ejercicios practicos",
    attendees: ["patricia.vega@design.com", "miguel.torres@design.com"],
    status: "Abierta",
    files: [],
    comments: [],
  },
  {
    id: "12",
    title: "Capacitacion Nuevas Herramientas",
    organizer: "Roberto Silva",
    company: "Training Co",
    startTime: getRelativeDate(4, 10, 0),
    endTime: getRelativeDate(4, 12, 0),
    description: "Capacitacion sobre nuevas herramientas de productividad",
    attendees: ["roberto.silva@training.com", "ana.garcia@techcorp.com"],
    status: "Abierta",
    files: [],
    comments: [],
  },
  {
    id: "13",
    title: "Sync Semanal de Equipos",
    organizer: "Sofia Ruiz",
    company: "Consulting Group",
    startTime: getRelativeDate(5, 9, 0),
    endTime: getRelativeDate(5, 10, 0),
    description: "Sincronizacion semanal entre equipos de desarrollo y ventas",
    attendees: ["sofia.ruiz@salescorp.com", "carlos.lopez@innovasoft.com", "pedro.sanchez@devstudio.com"],
    status: "Opcional",
    files: [],
    comments: [],
  },
  // === SEMANA SIGUIENTE (+7 a +13 dias) ===
  {
    id: "14",
    title: "Revision de Proyecto Cliente ABC",
    organizer: "Sofia Ruiz",
    company: "Consulting Group",
    startTime: getRelativeDate(7, 9, 30),
    endTime: getRelativeDate(7, 11, 0),
    description: "Revision del avance del proyecto con el cliente ABC",
    attendees: ["sofia.ruiz@salescorp.com", "luis.martin@salescorp.com"],
    status: "Opcional",
    files: [],
    comments: [],
  },
  {
    id: "15",
    title: "Planning Sprint 6",
    organizer: "Pedro Sanchez",
    company: "DevStudio",
    startTime: getRelativeDate(8, 10, 0),
    endTime: getRelativeDate(8, 12, 30),
    description: "Planificacion de tareas y historias para el sprint 6",
    attendees: ["pedro.sanchez@devstudio.com", "maria.rodriguez@devstudio.com", "carlos.lopez@innovasoft.com"],
    status: "Abierta",
    files: [],
    comments: [],
  },
  {
    id: "16",
    title: "Presentacion de Marca",
    organizer: "Patricia Vega",
    company: "Design Studio",
    startTime: getRelativeDate(9, 14, 0),
    endTime: getRelativeDate(9, 16, 0),
    description: "Presentacion de nueva identidad de marca al cliente",
    attendees: ["patricia.vega@design.com", "ana.garcia@techcorp.com"],
    status: "Abierta",
    files: [],
    comments: [],
  },
  {
    id: "17",
    title: "Taller de Metodologias Agiles",
    organizer: "Roberto Silva",
    company: "Training Co",
    startTime: getRelativeDate(10, 9, 0),
    endTime: getRelativeDate(10, 13, 0),
    description: "Taller practico sobre Scrum y Kanban para equipos de desarrollo",
    attendees: ["roberto.silva@training.com", "pedro.sanchez@devstudio.com", "maria.rodriguez@devstudio.com"],
    status: "Abierta",
    files: [],
    comments: [],
  },
  {
    id: "18",
    title: "Demo Cliente Enterprise",
    organizer: "Luis Martin",
    company: "SalesCorp",
    startTime: getRelativeDate(11, 15, 0),
    endTime: getRelativeDate(11, 17, 0),
    description: "Demostracion del producto para cliente enterprise potencial",
    attendees: ["luis.martin@salescorp.com", "carlos.lopez@innovasoft.com", "ana.garcia@techcorp.com"],
    status: "Abierta",
    files: [],
    comments: [],
  },
  {
    id: "19",
    title: "Reunion Trimestral de Resultados",
    organizer: "Ana Garcia",
    company: "TechCorp",
    startTime: getRelativeDate(12, 10, 0),
    endTime: getRelativeDate(12, 12, 0),
    description: "Revision de resultados del trimestre y proyecciones",
    attendees: ["ana.garcia@techcorp.com", "luis.martin@salescorp.com", "patricia.vega@design.com", "roberto.silva@training.com"],
    status: "Abierta",
    files: [],
    comments: [],
  },
  {
    id: "20",
    title: "Cierre de Sprint 5",
    organizer: "Maria Rodriguez",
    company: "DevStudio",
    startTime: getRelativeDate(13, 14, 0),
    endTime: getRelativeDate(13, 15, 30),
    description: "Revision final y cierre del sprint 5 con demo a stakeholders",
    attendees: ["maria.rodriguez@devstudio.com", "pedro.sanchez@devstudio.com", "sofia.ruiz@salescorp.com"],
    status: "Abierta",
    files: [],
    comments: [],
  },
]

// Notificaciones de ejemplo distribuidas en las 3 semanas
export const generateSampleNotifications = (): Notification[] => [
  // Notificaciones de hoy
  {
    id: "notif-1",
    userId: "demo-user-1",
    meetingId: "7",
    message: "Reunion: Reunion de Planificacion Q2",
    organizer: "Ana Garcia",
    startTime: { seconds: Math.floor(getRelativeDate(0, 9, 0).getTime() / 1000), nanoseconds: 0 },
    status: "Abierta",
    seen: false,
    timestamp: { seconds: Math.floor(Date.now() / 1000), nanoseconds: 0 },
  },
  {
    id: "notif-2",
    userId: "demo-user-1",
    meetingId: "8",
    message: "Reunion: Demo del Producto v2.0",
    organizer: "Carlos Lopez",
    startTime: { seconds: Math.floor(getRelativeDate(0, 14, 0).getTime() / 1000), nanoseconds: 0 },
    status: "Opcional",
    seen: false,
    timestamp: { seconds: Math.floor(Date.now() / 1000 - 3600), nanoseconds: 0 },
  },
  // Notificaciones de esta semana
  {
    id: "notif-3",
    userId: "demo-user-1",
    meetingId: "11",
    message: "Reunion: Workshop de Diseno UX/UI",
    organizer: "Patricia Vega",
    startTime: { seconds: Math.floor(getRelativeDate(3, 15, 30).getTime() / 1000), nanoseconds: 0 },
    status: "Abierta",
    seen: true,
    timestamp: { seconds: Math.floor(Date.now() / 1000 - 7200), nanoseconds: 0 },
  },
  {
    id: "notif-4",
    userId: "demo-user-1",
    meetingId: "12",
    message: "Reunion: Capacitacion Nuevas Herramientas",
    organizer: "Roberto Silva",
    startTime: { seconds: Math.floor(getRelativeDate(4, 10, 0).getTime() / 1000), nanoseconds: 0 },
    status: "Abierta",
    seen: false,
    timestamp: { seconds: Math.floor(Date.now() / 1000 - 14400), nanoseconds: 0 },
  },
  // Notificaciones de la proxima semana
  {
    id: "notif-5",
    userId: "demo-user-1",
    meetingId: "15",
    message: "Reunion: Planning Sprint 6",
    organizer: "Pedro Sanchez",
    startTime: { seconds: Math.floor(getRelativeDate(8, 10, 0).getTime() / 1000), nanoseconds: 0 },
    status: "Abierta",
    seen: false,
    timestamp: { seconds: Math.floor(Date.now() / 1000 - 21600), nanoseconds: 0 },
  },
  {
    id: "notif-6",
    userId: "demo-user-1",
    meetingId: "19",
    message: "Reunion: Reunion Trimestral de Resultados",
    organizer: "Ana Garcia",
    startTime: { seconds: Math.floor(getRelativeDate(12, 10, 0).getTime() / 1000), nanoseconds: 0 },
    status: "Abierta",
    seen: true,
    timestamp: { seconds: Math.floor(Date.now() / 1000 - 43200), nanoseconds: 0 },
  },
]
